use crate::bus::MemoryInterface;
use crate::cpu::flags::{Condition, Flags};
use crate::cpu::registers::{Register16, Register16Mem, Register8};
use crate::cpu::CPU;

use super::registers::Register16Stk;

pub enum RstVec {
    RST00 = 0x00,
    RST08 = 0x08,
    RST10 = 0x10,
    RST18 = 0x18,
    RST20 = 0x20,
    RST28 = 0x28,
    RST30 = 0x30,
    RST38 = 0x38,
}


impl CPU {
    pub fn execute<M: MemoryInterface>(&mut self, opcode: u8, memory: &mut M) {
        match opcode {           
            //opcode file https://izik1.github.io/gbops/
            0x00 => self.nop(),
            0x01 => self.ld_r16_imm16(Register16::BC, memory),
            0x02 => self.ld_r16mem_a(Register16Mem::BC, memory),
            0x03 => self.inc_r16(Register16::BC),
            0x04 => self.inc_r8(Register8::B, memory),
            0x05 => self.dec_r8(Register8::B, memory),
            0x06 => self.ld_r8_imm8(Register8::B, memory),
            0x07 => self.rlca(),
            0x08 => self.ld_imm16_sp(memory),
            0x09 => self.add_hl_r16(Register16::BC),
            0x0A => self.ld_a_r16mem(Register16Mem::BC, memory),
            0x0B => self.dec_r16(Register16::BC),
            0x0C => self.inc_r8(Register8::C, memory),
            0x0D => self.dec_r8(Register8::C, memory),
            0x0E => self.ld_r8_imm8(Register8::C, memory),
            0x0F => self.rrca(),
    
            0x10 => self.stop(),
            0x11 => self.ld_r16_imm16(Register16::DE, memory),
            0x12 => self.ld_r16mem_a(Register16Mem::DE, memory),
            0x13 => self.inc_r16(Register16::DE),
            0x14 => self.inc_r8(Register8::D, memory),
            0x15 => self.dec_r8(Register8::D, memory),
            0x16 => self.ld_r8_imm8(Register8::D, memory),
            0x17 => self.rla(),
            0x18 => self.jr_imm8(memory),
            0x19 => self.add_hl_r16(Register16::DE),
            0x1A => self.ld_a_r16mem(Register16Mem::DE, memory),
            0x1B => self.dec_r16(Register16::DE),
            0x1C => self.inc_r8(Register8::E, memory),
            0x1D => self.dec_r8(Register8::E, memory),
            0x1E => self.ld_r8_imm8(Register8::E, memory),
            0x1F => self.rra(),
    
            0x20 => self.jr_cond_imm8(Condition::NZ, memory),
            0x21 => self.ld_r16_imm16(Register16::HL, memory),
            0x22 => self.ld_r16mem_a(Register16Mem::HLi, memory),
            0x23 => self.inc_r16(Register16::HL),
            0x24 => self.inc_r8(Register8::H, memory),
            0x25 => self.dec_r8(Register8::H, memory),
            0x26 => self.ld_r8_imm8(Register8::H, memory),
            0x27 => self.daa(memory),
            0x28 => self.jr_cond_imm8(Condition::Z, memory),
            0x29 => self.add_hl_r16(Register16::HL),
            0x2A => self.ld_a_r16mem(Register16Mem::HLi, memory),
            0x2B => self.dec_r16(Register16::HL),
            0x2C => self.inc_r8(Register8::L, memory),
            0x2D => self.dec_r8(Register8::L, memory),
            0x2E => self.ld_r8_imm8(Register8::L, memory),
            0x2F => self.cpl(),
    
            0x30 => self.jr_cond_imm8(Condition::NC, memory),
            0x31 => self.ld_r16_imm16(Register16::SP, memory),
            0x32 => self.ld_r16mem_a(Register16Mem::HLd, memory),
            0x33 => self.inc_r16(Register16::SP),
            0x34 => self.inc_r8(Register8::HLIndirect, memory),
            0x35 => self.dec_r8(Register8::HLIndirect, memory),
            0x36 => self.ld_r8_imm8(Register8::HLIndirect, memory),
            0x37 => self.scf(),
            0x38 => self.jr_cond_imm8(Condition::C, memory),
            0x39 => self.add_hl_r16(Register16::SP),
            0x3A => self.ld_a_r16mem(Register16Mem::HLd, memory),
            0x3B => self.dec_r16(Register16::SP),
            0x3C => self.inc_r8(Register8::A, memory),
            0x3D => self.dec_r8(Register8::A, memory),
            0x3E => self.ld_r8_imm8(Register8::A, memory),
            0x3F => self.ccf(),
    
            0x40 => self.ld_r8_r8(Register8::B, Register8::B, memory), // NOP
            0x41 => self.ld_r8_r8(Register8::B, Register8::C, memory),
            0x42 => self.ld_r8_r8(Register8::B, Register8::D, memory),
            0x43 => self.ld_r8_r8(Register8::B, Register8::E, memory),
            0x44 => self.ld_r8_r8(Register8::B, Register8::H, memory),
            0x45 => self.ld_r8_r8(Register8::B, Register8::L, memory),
            0x46 => self.ld_r8_r8(Register8::B, Register8::HLIndirect, memory),
            0x47 => self.ld_r8_r8(Register8::B, Register8::A, memory),
            0x48 => self.ld_r8_r8(Register8::C, Register8::B, memory),
            0x49 => self.ld_r8_r8(Register8::C, Register8::C, memory), // NOP
            0x4A => self.ld_r8_r8(Register8::C, Register8::D, memory),
            0x4B => self.ld_r8_r8(Register8::C, Register8::E, memory),
            0x4C => self.ld_r8_r8(Register8::C, Register8::H, memory),
            0x4D => self.ld_r8_r8(Register8::C, Register8::L, memory),
            0x4E => self.ld_r8_r8(Register8::C, Register8::HLIndirect, memory),
            0x4F => self.ld_r8_r8(Register8::C, Register8::A, memory),
    
            0x50 => self.ld_r8_r8(Register8::D, Register8::B, memory),
            0x51 => self.ld_r8_r8(Register8::D, Register8::C, memory),
            0x52 => self.ld_r8_r8(Register8::D, Register8::D, memory), // NOP
            0x53 => self.ld_r8_r8(Register8::D, Register8::E, memory),
            0x54 => self.ld_r8_r8(Register8::D, Register8::H, memory),
            0x55 => self.ld_r8_r8(Register8::D, Register8::L, memory),
            0x56 => self.ld_r8_r8(Register8::D, Register8::HLIndirect, memory),
            0x57 => self.ld_r8_r8(Register8::D, Register8::A, memory),
            0x58 => self.ld_r8_r8(Register8::E, Register8::B, memory),
            0x59 => self.ld_r8_r8(Register8::E, Register8::C, memory),
            0x5A => self.ld_r8_r8(Register8::E, Register8::D, memory),
            0x5B => self.ld_r8_r8(Register8::E, Register8::E, memory), // NOP
            0x5C => self.ld_r8_r8(Register8::E, Register8::H, memory),
            0x5D => self.ld_r8_r8(Register8::E, Register8::L, memory),
            0x5E => self.ld_r8_r8(Register8::E, Register8::HLIndirect, memory),
            0x5F => self.ld_r8_r8(Register8::E, Register8::A, memory),
    
            0x60 => self.ld_r8_r8(Register8::H, Register8::B, memory),
            0x61 => self.ld_r8_r8(Register8::H, Register8::C, memory),
            0x62 => self.ld_r8_r8(Register8::H, Register8::D, memory),
            0x63 => self.ld_r8_r8(Register8::H, Register8::E, memory),
            0x64 => self.ld_r8_r8(Register8::H, Register8::H, memory), // NOP
            0x65 => self.ld_r8_r8(Register8::H, Register8::L, memory),
            0x66 => self.ld_r8_r8(Register8::H, Register8::HLIndirect, memory),
            0x67 => self.ld_r8_r8(Register8::H, Register8::A, memory),
            0x68 => self.ld_r8_r8(Register8::L, Register8::B, memory),
            0x69 => self.ld_r8_r8(Register8::L, Register8::C, memory),
            0x6A => self.ld_r8_r8(Register8::L, Register8::D, memory),
            0x6B => self.ld_r8_r8(Register8::L, Register8::E, memory),
            0x6C => self.ld_r8_r8(Register8::L, Register8::H, memory),
            0x6D => self.ld_r8_r8(Register8::L, Register8::L, memory), // NOP
            0x6E => self.ld_r8_r8(Register8::L, Register8::HLIndirect, memory),
            0x6F => self.ld_r8_r8(Register8::L, Register8::A, memory),
    
            0x70 => self.ld_r8_r8(Register8::HLIndirect, Register8::B, memory),
            0x71 => self.ld_r8_r8(Register8::HLIndirect, Register8::C, memory),
            0x72 => self.ld_r8_r8(Register8::HLIndirect, Register8::D, memory),
            0x73 => self.ld_r8_r8(Register8::HLIndirect, Register8::E, memory),
            0x74 => self.ld_r8_r8(Register8::HLIndirect, Register8::H, memory),
            0x75 => self.ld_r8_r8(Register8::HLIndirect, Register8::L, memory),
            0x76 => self.halt(memory),
            0x77 => self.ld_r8_r8(Register8::HLIndirect, Register8::A, memory),
            0x78 => self.ld_r8_r8(Register8::A, Register8::B, memory),
            0x79 => self.ld_r8_r8(Register8::A, Register8::C, memory),
            0x7A => self.ld_r8_r8(Register8::A, Register8::D, memory),
            0x7B => self.ld_r8_r8(Register8::A, Register8::E, memory),
            0x7C => self.ld_r8_r8(Register8::A, Register8::H, memory),
            0x7D => self.ld_r8_r8(Register8::A, Register8::L, memory),
            0x7E => self.ld_r8_r8(Register8::A, Register8::HLIndirect, memory),
            0x7F => self.ld_r8_r8(Register8::A, Register8::A, memory), // NOP
    
            0x80 => self.add_a_r8(Register8::B, memory),
            0x81 => self.add_a_r8(Register8::C, memory),
            0x82 => self.add_a_r8(Register8::D, memory),
            0x83 => self.add_a_r8(Register8::E, memory),
            0x84 => self.add_a_r8(Register8::H, memory),
            0x85 => self.add_a_r8(Register8::L, memory),
            0x86 => self.add_a_r8(Register8::HLIndirect, memory),
            0x87 => self.add_a_r8(Register8::A, memory),
            0x88 => self.adc_a_r8(Register8::B, memory),
            0x89 => self.adc_a_r8(Register8::C, memory),
            0x8A => self.adc_a_r8(Register8::D, memory),
            0x8B => self.adc_a_r8(Register8::E, memory),
            0x8C => self.adc_a_r8(Register8::H, memory),
            0x8D => self.adc_a_r8(Register8::L, memory),
            0x8E => self.adc_a_r8(Register8::HLIndirect, memory),
            0x8F => self.adc_a_r8(Register8::A, memory),
    
            0x90 => self.sub_a_r8(Register8::B, memory),
            0x91 => self.sub_a_r8(Register8::C, memory),
            0x92 => self.sub_a_r8(Register8::D, memory),
            0x93 => self.sub_a_r8(Register8::E, memory),
            0x94 => self.sub_a_r8(Register8::H, memory),
            0x95 => self.sub_a_r8(Register8::L, memory),
            0x96 => self.sub_a_r8(Register8::HLIndirect, memory),
            0x97 => self.sub_a_r8(Register8::A, memory),
            0x98 => self.sbc_a_r8(Register8::B, memory),
            0x99 => self.sbc_a_r8(Register8::C, memory),
            0x9A => self.sbc_a_r8(Register8::D, memory),
            0x9B => self.sbc_a_r8(Register8::E, memory),
            0x9C => self.sbc_a_r8(Register8::H, memory),
            0x9D => self.sbc_a_r8(Register8::L, memory),
            0x9E => self.sbc_a_r8(Register8::HLIndirect, memory),
            0x9F => self.sbc_a_r8(Register8::A, memory),
    
            0xA0 => self.and_a_r8(Register8::B, memory),
            0xA1 => self.and_a_r8(Register8::C, memory),
            0xA2 => self.and_a_r8(Register8::D, memory),
            0xA3 => self.and_a_r8(Register8::E, memory),
            0xA4 => self.and_a_r8(Register8::H, memory),
            0xA5 => self.and_a_r8(Register8::L, memory),
            0xA6 => self.and_a_r8(Register8::HLIndirect, memory),
            0xA7 => self.and_a_r8(Register8::A, memory),
            0xA8 => self.xor_a_r8(Register8::B, memory),
            0xA9 => self.xor_a_r8(Register8::C, memory),
            0xAA => self.xor_a_r8(Register8::D, memory),
            0xAB => self.xor_a_r8(Register8::E, memory),
            0xAC => self.xor_a_r8(Register8::H, memory),
            0xAD => self.xor_a_r8(Register8::L, memory),
            0xAE => self.xor_a_r8(Register8::HLIndirect, memory),
            0xAF => self.xor_a_r8(Register8::A, memory),
    
            0xB0 => self.or_a_r8(Register8::B, memory),
            0xB1 => self.or_a_r8(Register8::C, memory),
            0xB2 => self.or_a_r8(Register8::D, memory),
            0xB3 => self.or_a_r8(Register8::E, memory),
            0xB4 => self.or_a_r8(Register8::H, memory),
            0xB5 => self.or_a_r8(Register8::L, memory),
            0xB6 => self.or_a_r8(Register8::HLIndirect, memory),
            0xB7 => self.or_a_r8(Register8::A, memory),
            0xB8 => self.cp_a_r8(Register8::B, memory),
            0xB9 => self.cp_a_r8(Register8::C, memory),
            0xBA => self.cp_a_r8(Register8::D, memory),
            0xBB => self.cp_a_r8(Register8::E, memory),
            0xBC => self.cp_a_r8(Register8::H, memory),
            0xBD => self.cp_a_r8(Register8::L, memory),
            0xBE => self.cp_a_r8(Register8::HLIndirect, memory),
            0xBF => self.cp_a_r8(Register8::A, memory),
    
            0xC0 => self.ret_cc(Condition::NZ, memory),
            0xC1 => self.pop_r16stk(Register16Stk::BC, memory),
            0xC2 => self.jp_cond_imm16(Condition::NZ, memory),
            0xC3 => self.jp_imm16(memory),
            0xC4 => self.call_cond_imm16(Condition::NZ, memory),
            0xC5 => self.push_r16stk(Register16Stk::BC, memory),
            0xC6 => self.add_a_imm8(memory),
            0xC7 => self.rst_tgt3(RstVec::RST00, memory),
            0xC8 => self.ret_cc(Condition::Z, memory),
            0xC9 => self.ret(memory),
            0xCA => self.jp_cond_imm16(Condition::Z, memory),
            0xCB => unreachable!(),
          
            0xCC => self.call_cond_imm16(Condition::Z, memory),
            0xCD => self.call_imm16(memory),
            0xCE => self.adc_a_imm8(memory),
            0xCF => self.rst_tgt3(RstVec::RST08, memory),
            
            0xD0 => self.ret_cc(Condition::NC, memory),
            0xD1 => self.pop_r16stk(Register16Stk::DE, memory),
            0xD2 => self.jp_cond_imm16(Condition::NC, memory),
            // $D3 invalid
            0xD4 => self.call_cond_imm16(Condition::NC, memory),
            0xD5 => self.push_r16stk(Register16Stk::DE, memory),
            0xD6 => self.sub_a_imm8(memory),
            0xD7 => self.rst_tgt3(RstVec::RST10, memory),
            0xD8 => self.ret_cc(Condition::C, memory),
            0xD9 => self.reti(memory),
            0xDA => self.jp_cond_imm16(Condition::C, memory),
            // $DB invalid
            0xDC => self.call_cond_imm16(Condition::C, memory),
            // $DD invalid
            0xDE => self.sbc_a_imm8(memory),
            0xDF => self.rst_tgt3(RstVec::RST18, memory),
            
            0xE0 => self.ldh_imm8_a(memory),
            0xE1 => self.pop_r16stk(Register16Stk::HL, memory),
            0xE2 => self.ldh_c_a(memory),
            // $E3 invalid
            // $E4 invalid
            0xE5 => self.push_r16stk(Register16Stk::HL, memory),
            0xE6 => self.and_a_imm8(memory),
            0xE7 => self.rst_tgt3(RstVec::RST20, memory),
            0xE8 => self.add_sp_imm8(memory),
            0xE9 => self.jp_hl(memory),
            0xEA => self.ld_imm16_a(memory),
            // $EB invalid
            // $EC invalid
            // $ED invalid
            0xEE => self.xor_a_imm8(memory),
            0xEF => self.rst_tgt3(RstVec::RST28, memory),
            
            0xF0 => self.ldh_a_imm8(memory),
            0xF1 => self.pop_r16stk(Register16Stk::AF, memory),
            0xF2 => self.ldh_a_c(memory),
            0xF3 => self.di(),
            // $F4 invalid
            0xF5 => self.push_r16stk(Register16Stk::AF, memory),
            0xF6 => self.or_a_imm8(memory),
            0xF7 => self.rst_tgt3(RstVec::RST30, memory),
            0xF8 => self.ld_hl_sp_plus_imm8(memory),
            0xF9 => self.ld_sp_hl(memory),
            0xFA => self.ld_a_imm16(memory),
            0xFB => self.ei(),
            // $FC invalid
            // $FD invalid
            0xFE => self.cp_a_imm8(memory),
            0xFF => self.rst_tgt3(RstVec::RST38, memory),
            
            // The following opcodes are invalid, and hard-lock the CPU until the console is powered off:
            // $D3, $DB, $DD, $E3, $E4, $EB, $EC, $ED, $F4, $FC, and $FD.
            _ => {
                println!("opcode: {:?}", opcode)
            }
        }
    }
    pub fn execute_cb<M: MemoryInterface>(&mut self, opcode: u8, memory: &mut M) {
        // $CB prefix instructions
        match opcode {
            0x00 => self.rlc_r8(Register8::B, memory),
            0x01 => self.rlc_r8(Register8::C, memory),
            0x02 => self.rlc_r8(Register8::D, memory),
            0x03 => self.rlc_r8(Register8::E, memory),
            0x04 => self.rlc_r8(Register8::H, memory),
            0x05 => self.rlc_r8(Register8::L, memory),
            0x06 => self.rlc_r8(Register8::HLIndirect, memory),
            0x07 => self.rlc_r8(Register8::A, memory),
            0x08 => self.rrc_r8(Register8::B, memory),
            0x09 => self.rrc_r8(Register8::C, memory),
            0x0A => self.rrc_r8(Register8::D, memory),
            0x0B => self.rrc_r8(Register8::E, memory),
            0x0C => self.rrc_r8(Register8::H, memory),
            0x0D => self.rrc_r8(Register8::L, memory),
            0x0E => self.rrc_r8(Register8::HLIndirect, memory),
            0x0F => self.rrc_r8(Register8::A, memory),
    
            0x10 => self.rl_r8(Register8::B, memory),
            0x11 => self.rl_r8(Register8::C, memory),
            0x12 => self.rl_r8(Register8::D, memory),
            0x13 => self.rl_r8(Register8::E, memory),
            0x14 => self.rl_r8(Register8::H, memory),
            0x15 => self.rl_r8(Register8::L, memory),
            0x16 => self.rl_r8(Register8::HLIndirect, memory),
            0x17 => self.rl_r8(Register8::A, memory),
            0x18 => self.rr_r8(Register8::B, memory),
            0x19 => self.rr_r8(Register8::C, memory),
            0x1A => self.rr_r8(Register8::D, memory),
            0x1B => self.rr_r8(Register8::E, memory),
            0x1C => self.rr_r8(Register8::H, memory),
            0x1D => self.rr_r8(Register8::L, memory),
            0x1E => self.rr_r8(Register8::HLIndirect, memory),
            0x1F => self.rr_r8(Register8::A, memory),
    
            0x20 => self.sla_r8(Register8::B, memory),
            0x21 => self.sla_r8(Register8::C, memory),
            0x22 => self.sla_r8(Register8::D, memory),
            0x23 => self.sla_r8(Register8::E, memory),
            0x24 => self.sla_r8(Register8::H, memory),
            0x25 => self.sla_r8(Register8::L, memory),
            0x26 => self.sla_r8(Register8::HLIndirect, memory),
            0x27 => self.sla_r8(Register8::A, memory),
            0x28 => self.sra_r8(Register8::B, memory),
            0x29 => self.sra_r8(Register8::C, memory),
            0x2A => self.sra_r8(Register8::D, memory),
            0x2B => self.sra_r8(Register8::E, memory),
            0x2C => self.sra_r8(Register8::H, memory),
            0x2D => self.sra_r8(Register8::L, memory),
            0x2E => self.sra_r8(Register8::HLIndirect, memory),
            0x2F => self.sra_r8(Register8::A, memory),
    
            0x30 => self.swap_r8(Register8::B, memory),
            0x31 => self.swap_r8(Register8::C, memory),
            0x32 => self.swap_r8(Register8::D, memory),
            0x33 => self.swap_r8(Register8::E, memory),
            0x34 => self.swap_r8(Register8::H, memory),
            0x35 => self.swap_r8(Register8::L, memory),
            0x36 => self.swap_r8(Register8::HLIndirect, memory),
            0x37 => self.swap_r8(Register8::A, memory),
            0x38 => self.srl_r8(Register8::B, memory),
            0x39 => self.srl_r8(Register8::C, memory),
            0x3A => self.srl_r8(Register8::D, memory),
            0x3B => self.srl_r8(Register8::E, memory),
            0x3C => self.srl_r8(Register8::H, memory),
            0x3D => self.srl_r8(Register8::L, memory),
            0x3E => self.srl_r8(Register8::HLIndirect, memory),
            0x3F => self.srl_r8(Register8::A, memory),
    
            0x40 => self.bit_b3_r8(Register8::B, 0, memory),
            0x41 => self.bit_b3_r8(Register8::C, 0, memory),
            0x42 => self.bit_b3_r8(Register8::D, 0, memory),
            0x43 => self.bit_b3_r8(Register8::E, 0, memory),
            0x44 => self.bit_b3_r8(Register8::H, 0, memory),
            0x45 => self.bit_b3_r8(Register8::L, 0, memory),
            0x46 => self.bit_b3_r8(Register8::HLIndirect, 0, memory),
            0x47 => self.bit_b3_r8(Register8::A, 0, memory),
            0x48 => self.bit_b3_r8(Register8::B, 1, memory),
            0x49 => self.bit_b3_r8(Register8::C, 1, memory),
            0x4A => self.bit_b3_r8(Register8::D, 1, memory),
            0x4B => self.bit_b3_r8(Register8::E, 1, memory),
            0x4C => self.bit_b3_r8(Register8::H, 1, memory),
            0x4D => self.bit_b3_r8(Register8::L, 1, memory),
            0x4E => self.bit_b3_r8(Register8::HLIndirect, 1, memory),
            0x4F => self.bit_b3_r8(Register8::A, 1, memory),
    
            0x50 => self.bit_b3_r8(Register8::B, 2, memory),
            0x51 => self.bit_b3_r8(Register8::C, 2, memory),
            0x52 => self.bit_b3_r8(Register8::D, 2, memory),
            0x53 => self.bit_b3_r8(Register8::E, 2, memory),
            0x54 => self.bit_b3_r8(Register8::H, 2, memory),
            0x55 => self.bit_b3_r8(Register8::L, 2, memory),
            0x56 => self.bit_b3_r8(Register8::HLIndirect, 2, memory),
            0x57 => self.bit_b3_r8(Register8::A, 2, memory),
            0x58 => self.bit_b3_r8(Register8::B, 3, memory),
            0x59 => self.bit_b3_r8(Register8::C, 3, memory),
            0x5A => self.bit_b3_r8(Register8::D, 3, memory),
            0x5B => self.bit_b3_r8(Register8::E, 3, memory),
            0x5C => self.bit_b3_r8(Register8::H, 3, memory),
            0x5D => self.bit_b3_r8(Register8::L, 3, memory),
            0x5E => self.bit_b3_r8(Register8::HLIndirect, 3, memory),
            0x5F => self.bit_b3_r8(Register8::A, 3, memory),
    
            0x60 => self.bit_b3_r8(Register8::B, 4, memory),
            0x61 => self.bit_b3_r8(Register8::C, 4, memory),
            0x62 => self.bit_b3_r8(Register8::D, 4, memory),
            0x63 => self.bit_b3_r8(Register8::E, 4, memory),
            0x64 => self.bit_b3_r8(Register8::H, 4, memory),
            0x65 => self.bit_b3_r8(Register8::L, 4, memory),
            0x66 => self.bit_b3_r8(Register8::HLIndirect, 4, memory),
            0x67 => self.bit_b3_r8(Register8::A, 4, memory),
            0x68 => self.bit_b3_r8(Register8::B, 5, memory),
            0x69 => self.bit_b3_r8(Register8::C, 5, memory),
            0x6A => self.bit_b3_r8(Register8::D, 5, memory),
            0x6B => self.bit_b3_r8(Register8::E, 5, memory),
            0x6C => self.bit_b3_r8(Register8::H, 5, memory),
            0x6D => self.bit_b3_r8(Register8::L, 5, memory),
            0x6E => self.bit_b3_r8(Register8::HLIndirect, 5, memory),
            0x6F => self.bit_b3_r8(Register8::A, 5, memory),
    
            0x70 => self.bit_b3_r8(Register8::B, 6, memory),
            0x71 => self.bit_b3_r8(Register8::C, 6, memory),
            0x72 => self.bit_b3_r8(Register8::D, 6, memory),
            0x73 => self.bit_b3_r8(Register8::E, 6, memory),
            0x74 => self.bit_b3_r8(Register8::H, 6, memory),
            0x75 => self.bit_b3_r8(Register8::L, 6, memory),
            0x76 => self.bit_b3_r8(Register8::HLIndirect, 6, memory),
            0x77 => self.bit_b3_r8(Register8::A, 6, memory),
            0x78 => self.bit_b3_r8(Register8::B, 7, memory),
            0x79 => self.bit_b3_r8(Register8::C, 7, memory),
            0x7A => self.bit_b3_r8(Register8::D, 7, memory),
            0x7B => self.bit_b3_r8(Register8::E, 7, memory),
            0x7C => self.bit_b3_r8(Register8::H, 7, memory),
            0x7D => self.bit_b3_r8(Register8::L, 7, memory),
            0x7E => self.bit_b3_r8(Register8::HLIndirect, 7, memory),
            0x7F => self.bit_b3_r8(Register8::A, 7, memory),
    
            0x80 => self.res_b3_r8(Register8::B, 0, memory),
            0x81 => self.res_b3_r8(Register8::C, 0, memory),
            0x82 => self.res_b3_r8(Register8::D, 0, memory),
            0x83 => self.res_b3_r8(Register8::E, 0, memory),
            0x84 => self.res_b3_r8(Register8::H, 0, memory),
            0x85 => self.res_b3_r8(Register8::L, 0, memory),
            0x86 => self.res_b3_r8(Register8::HLIndirect, 0, memory),
            0x87 => self.res_b3_r8(Register8::A, 0, memory),
            0x88 => self.res_b3_r8(Register8::B, 1, memory),
            0x89 => self.res_b3_r8(Register8::C, 1, memory),
            0x8A => self.res_b3_r8(Register8::D, 1, memory),
            0x8B => self.res_b3_r8(Register8::E, 1, memory),
            0x8C => self.res_b3_r8(Register8::H, 1, memory),
            0x8D => self.res_b3_r8(Register8::L, 1, memory),
            0x8E => self.res_b3_r8(Register8::HLIndirect, 1, memory),
            0x8F => self.res_b3_r8(Register8::A, 1, memory),
    
            0x90 => self.res_b3_r8(Register8::B, 2, memory),
            0x91 => self.res_b3_r8(Register8::C, 2, memory),
            0x92 => self.res_b3_r8(Register8::D, 2, memory),
            0x93 => self.res_b3_r8(Register8::E, 2, memory),
            0x94 => self.res_b3_r8(Register8::H, 2, memory),
            0x95 => self.res_b3_r8(Register8::L, 2, memory),
            0x96 => self.res_b3_r8(Register8::HLIndirect, 2, memory),
            0x97 => self.res_b3_r8(Register8::A, 2, memory),
            0x98 => self.res_b3_r8(Register8::B, 3, memory),
            0x99 => self.res_b3_r8(Register8::C, 3, memory),
            0x9A => self.res_b3_r8(Register8::D, 3, memory),
            0x9B => self.res_b3_r8(Register8::E, 3, memory),
            0x9C => self.res_b3_r8(Register8::H, 3, memory),
            0x9D => self.res_b3_r8(Register8::L, 3, memory),
            0x9E => self.res_b3_r8(Register8::HLIndirect, 3, memory),
            0x9F => self.res_b3_r8(Register8::A, 3, memory),
    
            0xA0 => self.res_b3_r8(Register8::B, 4, memory),
            0xA1 => self.res_b3_r8(Register8::C, 4, memory),
            0xA2 => self.res_b3_r8(Register8::D, 4, memory),
            0xA3 => self.res_b3_r8(Register8::E, 4, memory),
            0xA4 => self.res_b3_r8(Register8::H, 4, memory),
            0xA5 => self.res_b3_r8(Register8::L, 4, memory),
            0xA6 => self.res_b3_r8(Register8::HLIndirect, 4, memory),
            0xA7 => self.res_b3_r8(Register8::A, 4, memory),
            0xA8 => self.res_b3_r8(Register8::B, 5, memory),
            0xA9 => self.res_b3_r8(Register8::C, 5, memory),
            0xAA => self.res_b3_r8(Register8::D, 5, memory),
            0xAB => self.res_b3_r8(Register8::E, 5, memory),
            0xAC => self.res_b3_r8(Register8::H, 5, memory),
            0xAD => self.res_b3_r8(Register8::L, 5, memory),
            0xAE => self.res_b3_r8(Register8::HLIndirect, 5, memory),
            0xAF => self.res_b3_r8(Register8::A, 5, memory),
            0xB0 => self.res_b3_r8(Register8::B, 6, memory),
            0xB1 => self.res_b3_r8(Register8::C, 6, memory),
            0xB2 => self.res_b3_r8(Register8::D, 6, memory),
            0xB3 => self.res_b3_r8(Register8::E, 6, memory),
            0xB4 => self.res_b3_r8(Register8::H, 6, memory),
            0xB5 => self.res_b3_r8(Register8::L, 6, memory),
            0xB6 => self.res_b3_r8(Register8::HLIndirect, 6, memory),
            0xB7 => self.res_b3_r8(Register8::A, 6, memory),
            0xB8 => self.res_b3_r8(Register8::B, 7, memory),
            0xB9 => self.res_b3_r8(Register8::C, 7, memory),
            0xBA => self.res_b3_r8(Register8::D, 7, memory),
            0xBB => self.res_b3_r8(Register8::E, 7, memory),
            0xBC => self.res_b3_r8(Register8::H, 7, memory),
            0xBD => self.res_b3_r8(Register8::L, 7, memory),
            0xBE => self.res_b3_r8(Register8::HLIndirect, 7, memory),
            0xBF => self.res_b3_r8(Register8::A, 7, memory),
    
            0xC0 => self.set_b3_r8(Register8::B, 0, memory),
            0xC1 => self.set_b3_r8(Register8::C, 0, memory),
            0xC2 => self.set_b3_r8(Register8::D, 0, memory),
            0xC3 => self.set_b3_r8(Register8::E, 0, memory),
            0xC4 => self.set_b3_r8(Register8::H, 0, memory),
            0xC5 => self.set_b3_r8(Register8::L, 0, memory),
            0xC6 => self.set_b3_r8(Register8::HLIndirect, 0, memory),
            0xC7 => self.set_b3_r8(Register8::A, 0, memory),
            0xC8 => self.set_b3_r8(Register8::B, 1, memory),
            0xC9 => self.set_b3_r8(Register8::C, 1, memory),
            0xCA => self.set_b3_r8(Register8::D, 1, memory),
            0xCB => self.set_b3_r8(Register8::E, 1, memory),
            0xCC => self.set_b3_r8(Register8::H, 1, memory),
            0xCD => self.set_b3_r8(Register8::L, 1, memory),
            0xCE => self.set_b3_r8(Register8::HLIndirect, 1, memory),
            0xCF => self.set_b3_r8(Register8::A, 1, memory),
    
            0xD0 => self.set_b3_r8(Register8::B, 2, memory),
            0xD1 => self.set_b3_r8(Register8::C, 2, memory),
            0xD2 => self.set_b3_r8(Register8::D, 2, memory),
            0xD3 => self.set_b3_r8(Register8::E, 2, memory),
            0xD4 => self.set_b3_r8(Register8::H, 2, memory),
            0xD5 => self.set_b3_r8(Register8::L, 2, memory),
            0xD6 => self.set_b3_r8(Register8::HLIndirect, 2, memory),
            0xD7 => self.set_b3_r8(Register8::A, 2, memory),
            0xD8 => self.set_b3_r8(Register8::B, 3, memory),
            0xD9 => self.set_b3_r8(Register8::C, 3, memory),
            0xDA => self.set_b3_r8(Register8::D, 3, memory),
            0xDB => self.set_b3_r8(Register8::E, 3, memory),
            0xDC => self.set_b3_r8(Register8::H, 3, memory),
            0xDD => self.set_b3_r8(Register8::L, 3, memory),
            0xDE => self.set_b3_r8(Register8::HLIndirect, 3, memory),
            0xDF => self.set_b3_r8(Register8::A, 3, memory),
    
            0xE0 => self.set_b3_r8(Register8::B, 4, memory),
            0xE1 => self.set_b3_r8(Register8::C, 4, memory),
            0xE2 => self.set_b3_r8(Register8::D, 4, memory),
            0xE3 => self.set_b3_r8(Register8::E, 4, memory),
            0xE4 => self.set_b3_r8(Register8::H, 4, memory),
            0xE5 => self.set_b3_r8(Register8::L, 4, memory),
            0xE6 => self.set_b3_r8(Register8::HLIndirect, 4, memory),
            0xE7 => self.set_b3_r8(Register8::A, 4, memory),
            0xE8 => self.set_b3_r8(Register8::B, 5, memory),
            0xE9 => self.set_b3_r8(Register8::C, 5, memory),
            0xEA => self.set_b3_r8(Register8::D, 5, memory),
            0xEB => self.set_b3_r8(Register8::E, 5, memory),
            0xEC => self.set_b3_r8(Register8::H, 5, memory),
            0xED => self.set_b3_r8(Register8::L, 5, memory),
            0xEE => self.set_b3_r8(Register8::HLIndirect, 5, memory),
            0xEF => self.set_b3_r8(Register8::A, 5, memory),
    
            0xF0 => self.set_b3_r8(Register8::B, 6, memory),
            0xF1 => self.set_b3_r8(Register8::C, 6, memory),
            0xF2 => self.set_b3_r8(Register8::D, 6, memory),
            0xF3 => self.set_b3_r8(Register8::E, 6, memory),
            0xF4 => self.set_b3_r8(Register8::H, 6, memory),
            0xF5 => self.set_b3_r8(Register8::L, 6, memory),
            0xF6 => self.set_b3_r8(Register8::HLIndirect, 6, memory),
            0xF7 => self.set_b3_r8(Register8::A, 6, memory),
            0xF8 => self.set_b3_r8(Register8::B, 7, memory),
            0xF9 => self.set_b3_r8(Register8::C, 7, memory),
            0xFA => self.set_b3_r8(Register8::D, 7, memory),
            0xFB => self.set_b3_r8(Register8::E, 7, memory),
            0xFC => self.set_b3_r8(Register8::H, 7, memory),
            0xFD => self.set_b3_r8(Register8::L, 7, memory),
            0xFE => self.set_b3_r8(Register8::HLIndirect, 7, memory),
            0xFF => self.set_b3_r8(Register8::A, 7, memory),
        }
    }
    }