[package]
name = "sabiboy"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
minifb = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5"
minifb_fonts = "0.1.3"