services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80" # Serve on port 80 for production

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000" # API exposed on port 3000
    volumes:
      - ./backend:/app
      - ./games:/games 