services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8002:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./games:/games
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./backend/.env
    
    restart: unless-stopped