[package]
name = "gameboy_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27"
minifb_fonts = "0.1.3"
gameboy_core = { path = "../core" }
anyhow = "1.0.71"
cpal = "0.15.2"

[profile.release]
debug = false
lto = "thin"
opt-level = 3
panic = "abort"
codegen-units = 1
