[package]
name = "gameboy_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gameboy_core = { path = "../core" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["ImageData"] }